"use client";

import {
  SHARE_CARD_HEIGHT,
  SHARE_CARD_WIDTH,
} from "@/lib/constants";
import { hdArtworkUrl } from "@/lib/artwork";
import { motion } from "framer-motion";
import { AlbumCover } from "@/components/album-cover";
import Image from "next/image";
import { useState } from "react";

export function ShareCard({
  collectionId,
  artworkUrl,
  collectionName,
  artistName,
  finalScore,
  review,
  themeColor,
  glowIntensity = 0.5,
  id = "share-card",
  className = "",
}: {
  collectionId: number | string;
  artworkUrl?: string;
  collectionName: string;
  artistName: string;
  finalScore: number;
  review: string;
  themeColor: string;
  glowIntensity?: number;
  id?: string;
  className?: string;
}) {
  const [bgFailed, setBgFailed] = useState(false);
  const url = hdArtworkUrl(artworkUrl);
  /** 40%–60% 黑遮罩，随滑块光晕微调 */
  const overlayOpacity = 0.42 + glowIntensity * 0.16;

  return (
    <div
      id={id}
      className={`relative overflow-hidden rounded-2xl border border-white/30 shadow-2xl ${className}`}
      style={{
        width: SHARE_CARD_WIDTH,
        height: SHARE_CARD_HEIGHT,
        ["--album-theme-color" as string]: themeColor,
      }}
    >
      {/* 沉浸式虚化：封面铺满底层 + 高斯模糊 */}
      <div className="absolute inset-0 overflow-hidden" aria-hidden>
        {url && !bgFailed ? (
          <Image
            src={url}
            alt=""
            fill
            className="object-cover scale-[1.12]"
            style={{ filter: "blur(76px)" }}
            onError={() => setBgFailed(true)}
            unoptimized
            crossOrigin="anonymous"
            priority
          />
        ) : (
          <div
            className="absolute inset-0"
            style={{ backgroundColor: themeColor }}
          />
        )}
      </div>

      <div
        className="absolute inset-0"
        style={{ backgroundColor: `rgba(0, 0, 0, ${overlayOpacity})` }}
        aria-hidden
      />

      <div className="relative z-10 flex h-full flex-col p-8 text-white">
        <div className="flex items-center justify-between gap-4">
          <AlbumCover
            collectionId={collectionId}
            src={artworkUrl}
            alt={collectionName}
            className="h-56 w-56 shrink-0 rounded-lg shadow-lg ring-1 ring-white/30"
            size={224}
            sharedLayout={false}
          />
          <div className="flex shrink-0 items-center justify-end">
            <motion.span
              key={finalScore}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ type: "spring", stiffness: 300, damping: 20 }}
              className="text-9xl font-bold tabular-nums leading-none drop-shadow-sm"
            >
              {finalScore.toFixed(1)}
            </motion.span>
          </div>
        </div>

        <div className="mt-4">
          <h2 className="text-2xl font-bold uppercase tracking-wide leading-tight drop-shadow-sm">
            {collectionName}
          </h2>
          <p className="mt-1 text-sm text-white/75">{artistName}</p>
        </div>

        <div className="mt-2 min-h-[3rem]">
          {review ? (
            <p className="text-lg leading-relaxed text-white/80">{review}</p>
          ) : (
            <p className="text-lg italic text-white/50">写下你的乐评…</p>
          )}
        </div>

        <p className="mt-auto pt-4 text-[9px] uppercase tracking-[0.35em] text-white/45">
          GENERATED BY VIBE MUSIC SYSTEM
        </p>
      </div>
    </div>
  );
}
